language: objective-c
osx_image: xcode7.0

install:
  - git submodule deinit -f .
  - git pull
  - git submodule update --init --recursive
  - (cd measurement-kit/mobile/ios/; bash scripts/build.sh) 
