language: objective-c, c
osx_image: xcode7.0

# Handle git submodules yourself
git:
    submodules: false

before_install:
    - git submodule update --init --recursive

install:
  - (cd measurement-kit/mobile/ios/; bash scripts/build.sh) 
