language: objective-c
osx_image: xcode7.0

# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - git submodule update --init --recursive

install:
  - (cd measurement-kit/mobile/ios/; bash scripts/build.sh) 
